spring:
  application:
    name: SpringBootPractice
  datasource:
    url: jdbc:mysql://localhost:3306/petshop?useSSL=false&useUnicode=true&characterEncoding=UTF-8&allowPublicKeyRetrieval=true
    username: root
    password: root123
    driver-class-name: com.mysql.cj.jdbc.Driver
  messages:
    basename=messages: encoding=UTF-8
  mail:
    host: smtp.gmail.com
    port: 587
    username: chithanh03062001@gmail.com
    password: nnuikakcfmvivgln
    properties.mail.smtp:
      auth: true
      starttls.enable: true




  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: none # none , create , create-drop , update   Hibernate sẽ tự động cập nhật cơ sở dữ liệu dựa trên các thay đổi trong các entity.
    show-sql: true # hien thi cau sql hibernate thuic hien vs Database
server:
  port: 8888


